// ui_text.js – Interface multilingue
window.UI_TEXT = {
  fr: {
    sub: "Apprendre en vivant",
    lbl_native: "🌍 Votre langue maternelle",
    lbl_name: "✏️ Votre prénom",
    lbl_target: "🎯 Langue à apprendre",
    lbl_script: "✍️ Mode d'écriture",
    play: "✨ Commencer",
    menu_title: "Que voulez-vous faire ?",
    menu_sub: "Choisissez votre mode d'apprentissage",
    mb_village: "Village", mb_village_d: "Conversations IA + correcteur",
    mb_vocab: "Vocabulaire", mb_vocab_d: "Mots essentiels par catégories",
    mb_phrases: "Phrases", mb_phrases_d: "Expressions du quotidien",
    mb_grammar: "Grammaire", mb_grammar_d: "Règles et exemples",
    mb_dict: "Dictionnaire", mb_dict_d: "Traduction mot ou phrase",
    translate: "🌐 Traduire", favorite: "⭐ Favoris", skip: "⏭ Passer",
    enter_village: "🏘️ Entrer dans le village", proverb_of_day: "Proverbe du jour"
  },
  en: {
    sub: "Learn by living",
    lbl_native: "🌍 Your native language",
    lbl_name: "✏️ Your name",
    lbl_target: "🎯 Language to learn",
    lbl_script: "✍️ Writing mode",
    play: "✨ Start",
    menu_title: "What would you like to do?",
    menu_sub: "Choose your learning mode",
    mb_village: "Village", mb_village_d: "AI conversations + correction",
    mb_vocab: "Vocabulary", mb_vocab_d: "Essential words by category",
    mb_phrases: "Phrases", mb_phrases_d: "Everyday expressions",
    mb_grammar: "Grammar", mb_grammar_d: "Rules & examples",
    mb_dict: "Dictionary", mb_dict_d: "Word or phrase translation",
    translate: "🌐 Translate", favorite: "⭐ Favorite", skip: "⏭ Skip",
    enter_village: "🏘️ Enter village", proverb_of_day: "Proverb of the day"
  },
  es: {
    sub: "Aprender viviendo",
    lbl_native: "🌍 Tu lengua materna",
    lbl_name: "✏️ Tu nombre",
    lbl_target: "🎯 Idioma a aprender",
    lbl_script: "✍️ Modo de escritura",
    play: "✨ Comenzar",
    menu_title: "¿Qué deseas hacer?",
    menu_sub: "Elige tu modo de aprendizaje",
    mb_village: "Pueblo", mb_village_d: "Conversaciones IA + corrector",
    mb_vocab: "Vocabulario", mb_vocab_d: "Palabras esenciales por categorías",
    mb_phrases: "Frases", mb_phrases_d: "Expressions cotidianas",
    mb_grammar: "Gramática", mb_grammar_d: "Reglas y ejemplos",
    mb_dict: "Diccionario", mb_dict_d: "Traducción palabra o frase",
    translate: "🌐 Traducir", favorite: "⭐ Favorito", skip: "⏭ Saltar",
    enter_village: "🏘️ Entrar al pueblo", proverb_of_day: "Proverbio del día"
  },
  ht: {
    sub: "Aprann lè w ap viv",
    lbl_native: "🌍 Lang matènèl ou",
    lbl_name: "✏️ Non w",
    lbl_target: "🎯 Lang ou vle aprann",
    lbl_script: "✍️ Fason ekri",
    play: "✨ Kòmanse",
    menu_title: "Kisa ou vle fè?",
    menu_sub: "Chwazi mòd aprantisaj ou",
    mb_village: "Vilaj", mb_village_d: "Konvèsasyon IA + koreksyon",
    mb_vocab: "Vokabilè", mb_vocab_d: "Mo esansyèl pa kategori",
    mb_phrases: "Fraz", mb_phrases_d: "Ekspresyon chak jou",
    mb_grammar: "Gramè", mb_grammar_d: "Règ ak egzanp",
    mb_dict: "Diksyonè", mb_dict_d: "Tradiksyon mo oubyen fraz",
    translate: "🌐 Tradwi", favorite: "⭐ Favori", skip: "⏭ Sote",
    enter_village: "🏘️ Antre nan vilaj la", proverb_of_day: "Pwovèb jounen an"
  },
  de: {
    sub: "Lebe durch Lernen",
    lbl_native: "🌍 Deine Muttersprache",
    lbl_name: "✏️ Dein Name",
    lbl_target: "🎯 Zu lernende Sprache",
    lbl_script: "✍️ Schreibmodus",
    play: "✨ Starten",
    menu_title: "Was möchtest du tun?",
    menu_sub: "Wähle deinen Lernmodus",
    mb_village: "Dorf", mb_village_d: "KI-Gespräche + Korrektur",
    mb_vocab: "Wortschatz", mb_vocab_d: "Wichtige Wörter nach Kategorien",
    mb_phrases: "Sätze", mb_phrases_d: "Alltägliche Ausdrücke",
    mb_grammar: "Grammatik", mb_grammar_d: "Regeln und Beispiele",
    mb_dict: "Wörterbuch", mb_dict_d: "Wort- oder Satzübersetzung",
    translate: "🌐 Übersetzen", favorite: "⭐ Favorit", skip: "⏭ Überspringen",
    enter_village: "🏘️ Dorf betreten", proverb_of_day: "Sprichwort des Tages"
  },
  ru: {
    sub: "Учиться, живя",
    lbl_native: "🌍 Ваш родной язык",
    lbl_name: "✏️ Ваше имя",
    lbl_target: "🎯 Изучаемый язык",
    lbl_script: "✍️ Режим письма",
    play: "✨ Начать",
    menu_title: "Что вы хотите сделать?",
    menu_sub: "Выберите режим обучения",
    mb_village: "Деревня", mb_village_d: "ИИ-беседы + коррекция",
    mb_vocab: "Словарь", mb_vocab_d: "Основные слова по категориям",
    mb_phrases: "Фразы", mb_phrases_d: "Повседневные выражения",
    mb_grammar: "Грамматика", mb_grammar_d: "Правила и примеры",
    mb_dict: "Словарь", mb_dict_d: "Перевод слова или фразы",
    translate: "🌐 Перевести", favorite: "⭐ Избранное", skip: "⏭ Пропустить",
    enter_village: "🏘️ Войти в деревню", proverb_of_day: "Пословица дня"
  },
  zh: {
    sub: "在生活中学",
    lbl_native: "🌍 您的母语",
    lbl_name: "✏️ 您的名字",
    lbl_target: "🎯 要学习的语言",
    lbl_script: "✍️ 书写模式",
    play: "✨ 开始",
    menu_title: "您想做什么？",
    menu_sub: "选择学习模式",
    mb_village: "村庄", mb_village_d: "AI对话 + 纠正",
    mb_vocab: "词汇", mb_vocab_d: "按类别的基本词汇",
    mb_phrases: "短语", mb_phrases_d: "日常表达",
    mb_grammar: "语法", mb_grammar_d: "规则和例子",
    mb_dict: "词典", mb_dict_d: "单词或短语翻译",
    translate: "🌐 翻译", favorite: "⭐ 收藏", skip: "⏭ 跳过",
    enter_village: "🏘️ 进入村庄", proverb_of_day: "每日谚语"
  },
  ja: {
    sub: "生きながら学ぶ",
    lbl_native: "🌍 あなたの母語",
    lbl_name: "✏️ あなたの名前",
    lbl_target: "🎯 学ぶ言語",
    lbl_script: "✍️ 書記モード",
    play: "✨ 開始",
    menu_title: "何をしますか？",
    menu_sub: "学習モードを選択",
    mb_village: "村", mb_village_d: "AI会話 + 修正",
    mb_vocab: "語彙", mb_vocab_d: "カテゴリ別の基本単語",
    mb_phrases: "フレーズ", mb_phrases_d: "日常表現",
    mb_grammar: "文法", mb_grammar_d: "規則と例",
    mb_dict: "辞書", mb_dict_d: "単語・フレーズ翻訳",
    translate: "🌐 翻訳", favorite: "⭐ お気に入り", skip: "⏭ スキップ",
    enter_village: "🏘️ 村に入る", proverb_of_day: "今日のことわざ"
  }
};
